"""Adding employees table

Revision ID: 7d1dd4c6c444
Revises: b322fb126255
Create Date: 2021-03-20 21:18:14.743805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d1dd4c6c444'
down_revision = 'b322fb126255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=False),
    sa.Column('doj', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('account', sa.Column('ttt', sa.Integer(), nullable=True))
    op.add_column('account', sa.Column('ttt1', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'ttt1')
    op.drop_column('account', 'ttt')
    op.drop_table('employees')
    # ### end Alembic commands ###
